snc_redis:
    clients:
        default:
            # db 0; persisted; e.g. sessions
            type: predis
            alias: default
            dsn: "%env(string:REDIS_URL)%"
            logging: '%kernel.debug%'
            options:
                prefix: "%env(string:APP_NAME)%_"
        cache:
            # db 1; not persisted; e.g. caches
            type: predis
            alias: cache
            dsn: "%env(string:REDIS_URL)%/1"
            logging: false
            options:
                prefix: "%env(string:APP_NAME)%_"
    session:
        client: default
        prefix: "session_"
