# This file contains instructions for docker-compose to start services needed
# by tests.
#
# Requirements:
# - Create a docker-compose.test.yml file and define your required services
# - Create a .env.test.local-test config to make use of docker-composer services
# - Implement a test script inside composer.json
# - Define overwrites for your services (like mysql, redis, elastic)
#
version: "3"
services:
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: integration-test
      MYSQL_USER: admin
      MYSQL_PASSWORD: changeme
    #ports:
    #  - "20001:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: "20s"
      retries: 10
